version: '3.7'

services:
    express_graphql_app_dev:
        build:
            dockerfile: ./docker/dev/Dockerfile
            context: .
        volumes:
            - './src:/app/src'
        ports:
            - '8000:8000'
        command: yarn start:dev
        restart: always
